# Form implementation generated from reading ui file 'c:\Users\llual\Desktop\practicas\git\Practicas-Yebes\aplicacion\pruebas\Pruebas Interfaces\Versiones originales\interfazUno.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.calendario = QtWidgets.QCalendarWidget(parent=self.centralwidget)
        self.calendario.setGeometry(QtCore.QRect(110, 150, 461, 271))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.calendario.sizePolicy().hasHeightForWidth())
        self.calendario.setSizePolicy(sizePolicy)
        self.calendario.setStyleSheet("")
        self.calendario.setMinimumDate(QtCore.QDate(2025, 5, 1))
        self.calendario.setGridVisible(True)
        self.calendario.setSelectionMode(QtWidgets.QCalendarWidget.SelectionMode.SingleSelection)
        self.calendario.setObjectName("calendario")
        self.Fecha = QtWidgets.QDateEdit(parent=self.centralwidget)
        self.Fecha.setGeometry(QtCore.QRect(300, 460, 110, 22))
        self.Fecha.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.Fecha.setObjectName("Fecha")
        self.SigVentana = QtWidgets.QPushButton(parent=self.centralwidget)
        self.SigVentana.setGeometry(QtCore.QRect(520, 440, 121, 51))
        self.SigVentana.setStyleSheet("border-radius: 8px;\n"
"background-color: rgb(160, 162, 161);")
        self.SigVentana.setAutoDefault(False)
        self.SigVentana.setObjectName("SigVentana")
        self.Fechaselec = QtWidgets.QLabel(parent=self.centralwidget)
        self.Fechaselec.setGeometry(QtCore.QRect(110, 460, 191, 31))
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        self.Fechaselec.setFont(font)
        self.Fechaselec.setStyleSheet("")
        self.Fechaselec.setObjectName("Fechaselec")
        self.Cabecera = QtWidgets.QLabel(parent=self.centralwidget)
        self.Cabecera.setGeometry(QtCore.QRect(0, -10, 801, 101))
        font = QtGui.QFont()
        font.setFamily("Sitka")
        font.setPointSize(20)
        font.setBold(False)
        font.setItalic(False)
        self.Cabecera.setFont(font)
        self.Cabecera.setStyleSheet("background-color: rgb(33, 140, 255);\n"
"font: 600 28pt \"Segoe UI Variable Text Semibold\";\n"
"font: 20pt \"Sitka\";\n"
"border-radius: 15px;\n"
"")
        self.Cabecera.setObjectName("Cabecera")
        self.SelFecha = QtWidgets.QLabel(parent=self.centralwidget)
        self.SelFecha.setGeometry(QtCore.QRect(110, 110, 221, 31))
        self.SelFecha.setStyleSheet("color: rgb(0, 0, 0);")
        self.SelFecha.setObjectName("SelFecha")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.SigVentana.setText(_translate("MainWindow", "Confirmar"))
        self.Fechaselec.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:14pt; font-weight:700; color:#000000;\">Fecha selecionada:</span></p><p><br/></p><p><span style=\" font-size:14pt; font-weight:700; color:#ffffff;\"><br/></span></p></body></html>"))
        self.Cabecera.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:18pt; font-weight:700; color:#ffffff;\">Administrador lecturas </span><span style=\" font-size:18pt; font-weight:700; font-style:italic; color:#ffffff;\">YLARA </span></p></body></html>"))
        self.SelFecha.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:16pt; font-weight:700; font-style:italic; \">Seleccione Fecha</span></p></body></html>"))
