# Form implementation generated from reading ui file 'c:\Users\llual\Desktop\practicas\git\Practicas-Yebes\aplicacion\pruebas\Pruebas Interfaces\Versiones originales\satelites.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(921, 555)
        Form.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.BototnBorrar = QtWidgets.QPushButton(parent=Form)
        self.BototnBorrar.setGeometry(QtCore.QRect(610, 500, 161, 51))
        self.BototnBorrar.setStyleSheet("background-color: rgb(247, 16, 16);")
        self.BototnBorrar.setObjectName("BototnBorrar")
        self.fecha_entrada = QtWidgets.QLabel(parent=Form)
        self.fecha_entrada.setGeometry(QtCore.QRect(30, 110, 171, 31))
        self.fecha_entrada.setObjectName("fecha_entrada")
        self.BotonPocAuto = QtWidgets.QPushButton(parent=Form)
        self.BotonPocAuto.setGeometry(QtCore.QRect(450, 500, 151, 51))
        self.BotonPocAuto.setObjectName("BotonPocAuto")
        self.Cabecera = QtWidgets.QLabel(parent=Form)
        self.Cabecera.setGeometry(QtCore.QRect(0, 0, 921, 101))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiBold SemiConden")
        font.setPointSize(20)
        font.setBold(False)
        font.setItalic(False)
        self.Cabecera.setFont(font)
        self.Cabecera.setStyleSheet("background-color: rgb(33, 140, 255);\n"
"font: 20pt \"Bahnschrift SemiBold SemiConden\";\n"
"border-radius: 15px;\n"
"")
        self.Cabecera.setObjectName("Cabecera")
        self.BotonProcMan = QtWidgets.QPushButton(parent=Form)
        self.BotonProcMan.setGeometry(QtCore.QRect(270, 500, 161, 51))
        self.BotonProcMan.setObjectName("BotonProcMan")
        self.BotonSubir = QtWidgets.QPushButton(parent=Form)
        self.BotonSubir.setGeometry(QtCore.QRect(60, 500, 121, 51))
        self.BotonSubir.setStyleSheet("background-color: rgb(153, 255, 89);")
        self.BotonSubir.setObjectName("BotonSubir")
        self.tablaSatelites = QtWidgets.QTableWidget(parent=Form)
        self.tablaSatelites.setGeometry(QtCore.QRect(25, 150, 871, 341))
        self.tablaSatelites.setObjectName("tablaSatelites")
        self.tablaSatelites.setColumnCount(0)
        self.tablaSatelites.setRowCount(0)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.BototnBorrar.setText(_translate("Form", "Borrar"))
        self.fecha_entrada.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:14pt; font-weight:700;\">Fecha: 14/01/2003</span></p></body></html>"))
        self.BotonPocAuto.setText(_translate("Form", "Procesado Automatico"))
        self.Cabecera.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" color:#ffffff;\">Satelites de las sesiones seleccionadas</span></p></body></html>"))
        self.BotonProcMan.setText(_translate("Form", "Procesado Manual"))
        self.BotonSubir.setText(_translate("Form", "Subir"))
