# Form implementation generated from reading ui file 'c:\Users\llual\Desktop\practicas\git\Practicas-Yebes\aplicacion\pruebas\Pruebas Interfaces\Versiones originales\sesiones.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(812, 541)
        self.BotonVeri = QtWidgets.QPushButton(parent=Form)
        self.BotonVeri.setGeometry(QtCore.QRect(490, 230, 161, 51))
        self.BotonVeri.setObjectName("BotonVeri")
        self.listaCarpetas = QtWidgets.QListWidget(parent=Form)
        self.listaCarpetas.setGeometry(QtCore.QRect(30, 150, 441, 371))
        self.listaCarpetas.setObjectName("listaCarpetas")
        self.fecha_entrada = QtWidgets.QLabel(parent=Form)
        self.fecha_entrada.setGeometry(QtCore.QRect(30, 110, 171, 31))
        self.fecha_entrada.setObjectName("fecha_entrada")
        self.BotonRecargar = QtWidgets.QPushButton(parent=Form)
        self.BotonRecargar.setGeometry(QtCore.QRect(490, 160, 121, 51))
        self.BotonRecargar.setObjectName("BotonRecargar")
        self.Cabecera = QtWidgets.QLabel(parent=Form)
        self.Cabecera.setGeometry(QtCore.QRect(0, 0, 811, 101))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiBold SemiConden")
        font.setPointSize(20)
        font.setBold(False)
        font.setItalic(False)
        self.Cabecera.setFont(font)
        self.Cabecera.setStyleSheet("background-color: rgb(33, 140, 255);\n"
"font: 20pt \"Bahnschrift SemiBold SemiConden\";\n"
"border-radius: 15px;\n"
"")
        self.Cabecera.setObjectName("Cabecera")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.BotonVeri.setText(_translate("Form", "Verificar"))
        self.fecha_entrada.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:14pt; font-weight:700;\">Fecha: 14/01/2003</span></p></body></html>"))
        self.BotonRecargar.setText(_translate("Form", "Recargar"))
        self.Cabecera.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" color:#ffffff;\">Seleccione las sesiones con las que desea trabajar</span></p></body></html>"))
