# Form implementation generated from reading ui file 'c:\Users\llual\Desktop\practicas\git\Practicas-Yebes\aplicacion\pruebas\Pruebas Interfaces\satelites.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(921, 555)
        Form.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        Form.setStyleSheet("QPushButton {\n"
"    min-height: 40px;\n"
"}\n"
"")
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setContentsMargins(0, 0, 0, -1)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(parent=Form)
        self.frame.setMinimumSize(QtCore.QSize(0, 120))
        self.frame.setMaximumSize(QtCore.QSize(16777215, 101))
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.frame.setObjectName("frame")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.Cabecera = QtWidgets.QLabel(parent=self.frame)
        self.Cabecera.setMinimumSize(QtCore.QSize(0, 120))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiBold SemiConden")
        font.setPointSize(20)
        font.setBold(False)
        font.setItalic(False)
        self.Cabecera.setFont(font)
        self.Cabecera.setStyleSheet("background-color: rgb(33, 140, 255);\n"
"font: 20pt \"Bahnschrift SemiBold SemiConden\";\n"
"border-radius: 15px;\n"
"")
        self.Cabecera.setObjectName("Cabecera")
        self.verticalLayout_3.addWidget(self.Cabecera)
        self.verticalLayout.addWidget(self.frame)
        self.frame_2 = QtWidgets.QFrame(parent=Form)
        self.frame_2.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_2.setContentsMargins(-1, 22, -1, -1)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.fecha_entrada = QtWidgets.QLabel(parent=self.frame_2)
        self.fecha_entrada.setObjectName("fecha_entrada")
        self.verticalLayout_2.addWidget(self.fecha_entrada, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.tablaSatelites = QtWidgets.QTableWidget(parent=self.frame_2)
        self.tablaSatelites.setObjectName("tablaSatelites")
        self.tablaSatelites.setColumnCount(0)
        self.tablaSatelites.setRowCount(0)
        self.verticalLayout_2.addWidget(self.tablaSatelites)
        self.verticalLayout.addWidget(self.frame_2)
        self.frame_3 = QtWidgets.QFrame(parent=Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_3.sizePolicy().hasHeightForWidth())
        self.frame_3.setSizePolicy(sizePolicy)
        self.frame_3.setMinimumSize(QtCore.QSize(0, 74))
        self.frame_3.setMaximumSize(QtCore.QSize(16777215, 74))
        self.frame_3.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout.setContentsMargins(9, 0, 9, 0)
        self.horizontalLayout.setSpacing(26)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.BotonSubir = QtWidgets.QPushButton(parent=self.frame_3)
        self.BotonSubir.setMinimumSize(QtCore.QSize(0, 42))
        self.BotonSubir.setStyleSheet("background-color: rgb(153, 255, 89);\n"
"")
        self.BotonSubir.setObjectName("BotonSubir")
        self.horizontalLayout.addWidget(self.BotonSubir)
        self.BotonProcMan = QtWidgets.QPushButton(parent=self.frame_3)
        self.BotonProcMan.setObjectName("BotonProcMan")
        self.horizontalLayout.addWidget(self.BotonProcMan)
        self.BotonPocAuto = QtWidgets.QPushButton(parent=self.frame_3)
        self.BotonPocAuto.setObjectName("BotonPocAuto")
        self.horizontalLayout.addWidget(self.BotonPocAuto)
        self.BototnBorrar = QtWidgets.QPushButton(parent=self.frame_3)
        self.BototnBorrar.setStyleSheet("background-color: rgb(247, 16, 16);")
        self.BototnBorrar.setObjectName("BototnBorrar")
        self.horizontalLayout.addWidget(self.BototnBorrar)
        self.verticalLayout.addWidget(self.frame_3)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "IGM"))
        self.Cabecera.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:28pt; color:#ffffff;\">Satelites de las sesiones seleccionadas</span></p></body></html>"))
        self.fecha_entrada.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:14pt; font-weight:700;\">Fecha: 14/01/2003</span></p></body></html>"))
        self.BotonSubir.setText(_translate("Form", "Subir"))
        self.BotonProcMan.setText(_translate("Form", "Procesado Manual"))
        self.BotonPocAuto.setText(_translate("Form", "Procesado Automatico"))
        self.BototnBorrar.setText(_translate("Form", "Borrar"))
