# Form implementation generated from reading ui file 'c:\Users\llual\Desktop\practicas\git\Practicas-Yebes\aplicacion\pruebas\Pruebas Interfaces\sesiones.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(829, 594)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(parent=Form)
        self.frame.setMinimumSize(QtCore.QSize(0, 113))
        self.frame.setMaximumSize(QtCore.QSize(16777215, 113))
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.frame.setObjectName("frame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.Cabecera = QtWidgets.QLabel(parent=self.frame)
        self.Cabecera.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiBold SemiConden")
        font.setPointSize(20)
        font.setBold(False)
        font.setItalic(False)
        self.Cabecera.setFont(font)
        self.Cabecera.setStyleSheet("background-color: rgb(33, 140, 255);\n"
"font: 20pt \"Bahnschrift SemiBold SemiConden\";\n"
"border-radius: 15px;\n"
"")
        self.Cabecera.setObjectName("Cabecera")
        self.verticalLayout_2.addWidget(self.Cabecera)
        self.verticalLayout.addWidget(self.frame)
        self.frame_2 = QtWidgets.QFrame(parent=Form)
        self.frame_2.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame_4 = QtWidgets.QFrame(parent=self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_4.sizePolicy().hasHeightForWidth())
        self.frame_4.setSizePolicy(sizePolicy)
        self.frame_4.setMinimumSize(QtCore.QSize(552, 450))
        self.frame_4.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.frame_4.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.frame_4.setObjectName("frame_4")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_4)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.fecha_entrada = QtWidgets.QLabel(parent=self.frame_4)
        self.fecha_entrada.setMinimumSize(QtCore.QSize(171, 31))
        self.fecha_entrada.setObjectName("fecha_entrada")
        self.verticalLayout_3.addWidget(self.fecha_entrada)
        self.listaCarpetas = QtWidgets.QListWidget(parent=self.frame_4)
        self.listaCarpetas.setMinimumSize(QtCore.QSize(531, 30))
        self.listaCarpetas.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.listaCarpetas.setObjectName("listaCarpetas")
        self.verticalLayout_3.addWidget(self.listaCarpetas)
        self.horizontalLayout.addWidget(self.frame_4, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.frame_3 = QtWidgets.QFrame(parent=self.frame_2)
        self.frame_3.setMaximumSize(QtCore.QSize(500, 16777215))
        self.frame_3.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_4.addItem(spacerItem)
        self.BotonRecargar = QtWidgets.QPushButton(parent=self.frame_3)
        self.BotonRecargar.setMinimumSize(QtCore.QSize(121, 51))
        self.BotonRecargar.setObjectName("BotonRecargar")
        self.verticalLayout_4.addWidget(self.BotonRecargar)
        self.BotonVeri = QtWidgets.QPushButton(parent=self.frame_3)
        self.BotonVeri.setMinimumSize(QtCore.QSize(161, 51))
        self.BotonVeri.setObjectName("BotonVeri")
        self.verticalLayout_4.addWidget(self.BotonVeri)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_4.addItem(spacerItem1)
        self.horizontalLayout.addWidget(self.frame_3)
        self.verticalLayout.addWidget(self.frame_2, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.Cabecera.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" color:#ffffff;\">Seleccione las sesiones con las que desea trabajar</span></p></body></html>"))
        self.fecha_entrada.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:14pt; font-weight:700;\">Fecha: 14/01/2003</span></p></body></html>"))
        self.BotonRecargar.setText(_translate("Form", "Recargar"))
        self.BotonVeri.setText(_translate("Form", "Verificar"))
