# Form implementation generated from reading ui file 'Window_Main.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
from vistas.logos.logos_rsc import *
from vistas.logos.resource_rc import *

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(886, 600)
        MainWindow.setStyleSheet("background-color: rgb(85, 0, 255);")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setStyleSheet("background-color: rgb(58, 87, 117);")
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.QFrame_Cabecera = QtWidgets.QFrame(parent=self.centralwidget)
        self.QFrame_Cabecera.setMinimumSize(QtCore.QSize(0, 113))
        self.QFrame_Cabecera.setMaximumSize(QtCore.QSize(16777215, 113))
        self.QFrame_Cabecera.setStyleSheet("\n"
"background-color: rgb(58, 87, 117);\n"
"")
        self.QFrame_Cabecera.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.QFrame_Cabecera.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.QFrame_Cabecera.setObjectName("QFrame_Cabecera")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.QFrame_Cabecera)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.QFrame_Logo = QtWidgets.QFrame(parent=self.QFrame_Cabecera)
        self.QFrame_Logo.setMinimumSize(QtCore.QSize(0, 0))
        self.QFrame_Logo.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.QFrame_Logo.setStyleSheet("border-radius:5px")
        self.QFrame_Logo.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.QFrame_Logo.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.QFrame_Logo.setObjectName("QFrame_Logo")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.QFrame_Logo)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label = QtWidgets.QLabel(parent=self.QFrame_Logo)
        self.label.setMinimumSize(QtCore.QSize(148, 0))
        self.label.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.label.setAutoFillBackground(False)
        self.label.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"image: url(:/logoYapagar/Logo YLARA.png);")
        self.label.setText("")
        self.label.setTextFormat(QtCore.Qt.TextFormat.AutoText)
        self.label.setScaledContents(False)
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setWordWrap(False)
        self.label.setObjectName("label")
        self.horizontalLayout_4.addWidget(self.label)
        self.horizontalLayout_3.addWidget(self.QFrame_Logo)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.Cabecera = QtWidgets.QLabel(parent=self.QFrame_Cabecera)
        font = QtGui.QFont()
        font.setFamily("Sitka")
        font.setPointSize(20)
        font.setBold(False)
        font.setItalic(False)
        self.Cabecera.setFont(font)
        self.Cabecera.setStyleSheet("font: 20pt \"Sitka\";\n"
"")
        self.Cabecera.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.Cabecera.setObjectName("Cabecera")
        self.horizontalLayout_3.addWidget(self.Cabecera)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.horizontalLayout_3.setStretch(0, 4)
        self.horizontalLayout_3.setStretch(1, 5)
        self.horizontalLayout_3.setStretch(2, 2)
        self.horizontalLayout_3.setStretch(3, 5)
        self.verticalLayout.addWidget(self.QFrame_Cabecera)
        self.QFrame_Central = QtWidgets.QFrame(parent=self.centralwidget)
        self.QFrame_Central.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.QFrame_Central.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.QFrame_Central.setObjectName("QFrame_Central")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.QFrame_Central)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.QFrame_Botones = QtWidgets.QFrame(parent=self.QFrame_Central)
        self.QFrame_Botones.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.QFrame_Botones.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.QFrame_Botones.setObjectName("QFrame_Botones")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.QFrame_Botones)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame = QtWidgets.QFrame(parent=self.QFrame_Botones)
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.BotonCalendario = QtWidgets.QPushButton(parent=self.frame)
        self.BotonCalendario.setMinimumSize(QtCore.QSize(5, 40))
        self.BotonCalendario.setStyleSheet("QPushButton{\n"
"    \n"
"    \n"
"    background-color: rgb(170, 255, 0);\n"
"    border-style: outset;\n"
"    border-width: 2px;\n"
"    border-color: grey;\n"
"    border-radius: 10\n"
"}\n"
"QPushButton:hover {\n"
"    border-style: inset;\n"
"}\n"
"QPushButton:pressed{\n"
"    border-style: inset;\n"
"    \n"
"    background-color: rgb(159, 238, 0);\n"
"}")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icon/calendario.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.BotonCalendario.setIcon(icon)
        self.BotonCalendario.setObjectName("BotonCalendario")
        self.verticalLayout_3.addWidget(self.BotonCalendario)
        self.BotonSesiones = QtWidgets.QPushButton(parent=self.frame)
        self.BotonSesiones.setMinimumSize(QtCore.QSize(0, 40))
        self.BotonSesiones.setStyleSheet("QPushButton{\n"
"    \n"
"    border-style: outset;\n"
"    background-color: rgb(255, 170, 0);\n"
"    border-width: 2px;\n"
"    border-color: grey;\n"
"    border-radius: 10\n"
"}\n"
"QPushButton:hover {\n"
"    border-style: inset;\n"
"}\n"
"QPushButton:pressed{\n"
"    border-style: inset;\n"
"    \n"
"    background-color: rgb(236, 157, 0);\n"
"}")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icon/lista.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.BotonSesiones.setIcon(icon1)
        self.BotonSesiones.setObjectName("BotonSesiones")
        self.verticalLayout_3.addWidget(self.BotonSesiones)
        self.BotonPases = QtWidgets.QPushButton(parent=self.frame)
        self.BotonPases.setMinimumSize(QtCore.QSize(0, 40))
        self.BotonPases.setStyleSheet("QPushButton{\n"
"    \n"
"    background-color: rgb(85, 255, 255);\n"
"    border-style: outset;\n"
"    border-width: 2px;\n"
"    border-color: grey;\n"
"    border-radius: 10\n"
"}\n"
"QPushButton:hover {\n"
"    border-style: inset;\n"
"}\n"
"QPushButton:pressed{\n"
"    border-style: inset;\n"
"    \n"
"    background-color: rgb(73, 218, 218);\n"
"}")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icon/target_laser.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.BotonPases.setIcon(icon2)
        self.BotonPases.setObjectName("BotonPases")
        self.verticalLayout_3.addWidget(self.BotonPases)
        self.verticalLayout_2.addWidget(self.frame)
        self.frame_2 = QtWidgets.QFrame(parent=self.QFrame_Botones)
        self.frame_2.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.BotonCerrar = QtWidgets.QPushButton(parent=self.frame_2)
        self.BotonCerrar.setMaximumSize(QtCore.QSize(50, 16777215))
        self.BotonCerrar.setStyleSheet("QPushButton{\n"
"    background-color: red;\n"
"    border-style: outset;\n"
"    border-width: 2px;\n"
"    border-color: grey;\n"
"    border-radius: 10\n"
"}\n"
"QPushButton:hover {\n"
"    border-style: inset;\n"
"}\n"
"QPushButton:pressed{\n"
"    border-style: inset;\n"
"    background-color: rgb(207, 0, 0);\n"
"}")
        self.BotonCerrar.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/logoYapagar/apagar.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.BotonCerrar.setIcon(icon3)
        self.BotonCerrar.setIconSize(QtCore.QSize(24, 24))
        self.BotonCerrar.setObjectName("BotonCerrar")
        self.verticalLayout_4.addWidget(self.BotonCerrar)
        self.verticalLayout_2.addWidget(self.frame_2, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.verticalLayout_2.setStretch(0, 3)
        self.verticalLayout_2.setStretch(1, 1)
        self.horizontalLayout.addWidget(self.QFrame_Botones)
        self.QFrame_Contenido = QtWidgets.QFrame(parent=self.QFrame_Central)
        self.QFrame_Contenido.setStyleSheet("background-color: rgb(221, 221, 221);")
        self.QFrame_Contenido.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.QFrame_Contenido.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.QFrame_Contenido.setObjectName("QFrame_Contenido")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.QFrame_Contenido)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.horizontalLayout.addWidget(self.QFrame_Contenido)
        self.horizontalLayout.setStretch(0, 1)
        self.horizontalLayout.setStretch(1, 5)
        self.verticalLayout.addWidget(self.QFrame_Central)
        self.verticalLayout.setStretch(0, 1)
        self.verticalLayout.setStretch(1, 4)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Cabecera.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:26pt; font-weight:700; color:#ffffff;\">Administrador de Pases de YLARA</span></p></body></html>"))
        self.BotonCalendario.setText(_translate("MainWindow", "Calendario"))
        self.BotonSesiones.setText(_translate("MainWindow", "Sesiones"))
        self.BotonPases.setText(_translate("MainWindow", " Pases  "))
