# Form implementation generated from reading ui file 'Window_Calendario.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(856, 530)
        Form.setStyleSheet("background-color: rgb(221, 221, 221);")
        self.gridLayout_3 = QtWidgets.QGridLayout(Form)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.QFrame_Bajo = QtWidgets.QFrame(parent=Form)
        self.QFrame_Bajo.setMinimumSize(QtCore.QSize(0, 0))
        self.QFrame_Bajo.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.QFrame_Bajo.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.QFrame_Bajo.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.QFrame_Bajo.setObjectName("QFrame_Bajo")
        self.formLayout = QtWidgets.QFormLayout(self.QFrame_Bajo)
        self.formLayout.setObjectName("formLayout")
        self.Fechaselec = QtWidgets.QLabel(parent=self.QFrame_Bajo)
        self.Fechaselec.setMinimumSize(QtCore.QSize(191, 31))
        self.Fechaselec.setMaximumSize(QtCore.QSize(191, 31))
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        self.Fechaselec.setFont(font)
        self.Fechaselec.setStyleSheet("")
        self.Fechaselec.setObjectName("Fechaselec")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.LabelRole, self.Fechaselec)
        self.Fecha = QtWidgets.QDateEdit(parent=self.QFrame_Bajo)
        self.Fecha.setMinimumSize(QtCore.QSize(110, 22))
        self.Fecha.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        self.Fecha.setFont(font)
        self.Fecha.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"font: 10pt \"Segoe UI\";\n"
"")
        self.Fecha.setObjectName("Fecha")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.FieldRole, self.Fecha)
        self.QFrame_Botones = QtWidgets.QFrame(parent=self.QFrame_Bajo)
        self.QFrame_Botones.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.QFrame_Botones.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.QFrame_Botones.setObjectName("QFrame_Botones")
        self.gridLayout = QtWidgets.QGridLayout(self.QFrame_Botones)
        self.gridLayout.setContentsMargins(0, -1, -1, -1)
        self.gridLayout.setObjectName("gridLayout")
        self.SigVentana = QtWidgets.QPushButton(parent=self.QFrame_Botones)
        self.SigVentana.setMinimumSize(QtCore.QSize(121, 52))
        self.SigVentana.setMaximumSize(QtCore.QSize(121, 52))
        self.SigVentana.setStyleSheet("QPushButton{\n"
"    background-color: rgb(255, 255, 255);\n"
"    border-style: outset;\n"
"    border-width: 2px;\n"
"    border-color: grey;\n"
"    border-radius: 10\n"
"}\n"
"QPushButton:hover {\n"
"    border-style: inset;\n"
"}\n"
"QPushButton:pressed{\n"
"    border-style: inset;\n"
"    \n"
"    background-color: rgb(239, 239, 239);\n"
"}")
        self.SigVentana.setAutoDefault(False)
        self.SigVentana.setObjectName("SigVentana")
        self.gridLayout.addWidget(self.SigVentana, 0, 2, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout.addItem(spacerItem, 0, 3, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout.addItem(spacerItem1, 0, 1, 1, 1)
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.SpanningRole, self.QFrame_Botones)
        self.gridLayout_3.addWidget(self.QFrame_Bajo, 1, 1, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout_3.addItem(spacerItem2, 1, 0, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout_3.addItem(spacerItem3, 1, 2, 1, 1)
        self.QFram_Calendario = QtWidgets.QFrame(parent=Form)
        self.QFram_Calendario.setMinimumSize(QtCore.QSize(545, 0))
        self.QFram_Calendario.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.QFram_Calendario.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.QFram_Calendario.setObjectName("QFram_Calendario")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.QFram_Calendario)
        self.verticalLayout_2.setContentsMargins(0, 7, 0, 0)
        self.verticalLayout_2.setSpacing(10)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.SelFecha = QtWidgets.QLabel(parent=self.QFram_Calendario)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SelFecha.sizePolicy().hasHeightForWidth())
        self.SelFecha.setSizePolicy(sizePolicy)
        self.SelFecha.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.SelFecha.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.SelFecha.setStyleSheet("color: rgb(0, 0, 0);")
        self.SelFecha.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.SelFecha.setObjectName("SelFecha")
        self.verticalLayout_2.addWidget(self.SelFecha, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.calendario = QtWidgets.QCalendarWidget(parent=self.QFram_Calendario)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.calendario.sizePolicy().hasHeightForWidth())
        self.calendario.setSizePolicy(sizePolicy)
        self.calendario.setMinimumSize(QtCore.QSize(747, 288))
        self.calendario.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.calendario.setFont(font)
        self.calendario.setStyleSheet("/* Style for header area  ####################################################*/ \n"
"\n"
"QCalendarWidget QWidget {\n"
"     alternate-background-color: #4e7be4;\n"
"    background-color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"/* style for top navigation area ###############################################*/ \n"
"\n"
"#qt_calendar_navigationbar {\n"
"    background-color: #fff;\n"
"    border: 2px solid  #B8E2FF;\n"
"    border-bottom: 0px;\n"
"    border-top-left-radius: 5px;\n"
"    border-top-right-radius: 5px;\n"
"}\n"
"\n"
"/* style for month change buttons ############################################ */\n"
"/* style for month change buttons ############################################ */\n"
"\n"
"#qt_calendar_prevmonth, \n"
"#qt_calendar_nextmonth {\n"
"    /* border delete */\n"
"    border: none;  \n"
"    /* delete default icons */\n"
"    qproperty-icon: none; \n"
"    \n"
"    min-width: 13px;\n"
"    max-width: 13px;\n"
"    min-height: 13px;\n"
"    max-height: 13px;\n"
"\n"
"    border-radius: 5px; \n"
"    /* set background transparent */\n"
"    background-color: transparent; \n"
"    padding: 5px;\n"
"}\n"
"\n"
"/* style for pre month button ############################################ */\n"
"\n"
"#qt_calendar_prevmonth {\n"
"    /* set text for button */\n"
"    /*qproperty-text: &quot;&gt;&quot;;*/\n"
"    margin-left:5px;\n"
"    image: url(:/icon/arrow-119-48.ico);\n"
"}\n"
"\n"
"/* style for next month button ########################################### */\n"
"#qt_calendar_nextmonth {\n"
"    margin-right:5px;\n"
"    image: url(:/icon/arrow-19-48.ico);\n"
"    /* qproperty-text: &quot;&gt;&quot;; */\n"
"}\n"
"#qt_calendar_prevmonth:hover, \n"
"#qt_calendar_nextmonth:hover {\n"
"    background-color: #55aaff;\n"
"}\n"
"\n"
"#qt_calendar_prevmonth:pressed, \n"
"#qt_calendar_nextmonth:pressed {\n"
"    background-color: rgba(235, 235, 235, 100);\n"
"}\n"
"\n"
"/* Style for month and yeat buttons #################################### */\n"
"\n"
"#qt_calendar_yearbutton {\n"
"    color: #000;\n"
"    margin:5px;\n"
"    border-radius: 5px;\n"
"    font-size: 13px;\n"
"    padding:0px 10px;\n"
"}\n"
"\n"
" #qt_calendar_monthbutton {\n"
"    width: 110px;\n"
"    color: #000;\n"
"    font-size: 13px;\n"
"    margin:5px 0px;\n"
"    border-radius: 5px;\n"
"    padding:0px 2px;\n"
"}\n"
"\n"
"#qt_calendar_yearbutton:hover, \n"
"#qt_calendar_monthbutton:hover {\n"
"    background-color: #55aaff;\n"
"}\n"
"\n"
"#qt_calendar_yearbutton:pressed, \n"
"#qt_calendar_monthbutton:pressed {\n"
"    background-color: rgba(235, 235, 235, 100);\n"
"}\n"
"\n"
"/* Style for year input lineEdit ######################################*/\n"
"\n"
"#qt_calendar_yearedit {\n"
"    min-width: 53px;\n"
"    color: #000;\n"
"    background: transparent;\n"
"    font-size: 13px;\n"
"}\n"
"\n"
"/* Style for year change buttons ######################################*/\n"
"\n"
"#qt_calendar_yearedit::up-button { \n"
"    image: url(:/icon/arrow-151-48.ico);\n"
"    subcontrol-position: right;\n"
"}\n"
"\n"
"#qt_calendar_yearedit::down-button { \n"
"    image: url(:/icon/arrow-213-48.ico);\n"
"    subcontrol-position: left; \n"
"}\n"
"\n"
"#qt_calendar_yearedit::down-button, \n"
"#qt_calendar_yearedit::up-button {\n"
"    width:10px;\n"
"    padding: 0px 5px;\n"
"    border-radius:3px;\n"
"}\n"
"\n"
"#qt_calendar_yearedit::down-button:hover, \n"
"#qt_calendar_yearedit::up-button:hover {\n"
"    background-color: #55aaff;\n"
"}\n"
"/* Style for month select menu ##################################### */\n"
"\n"
"#calendarWidget QToolButton QMenu {\n"
"     background-color: white;\n"
"\n"
"}\n"
"#calendarWidget QToolButton QMenu::item {\n"
"    /*padding: 10px;*/\n"
"}\n"
" #calendarWidget QToolButton QMenu::item:selected:enabled {\n"
"    background-color: #55aaff;\n"
"}\n"
"\n"
"#calendarWidget QToolButton::menu-indicator {\n"
"    /* Remove toolButton arrow */\n"
"      /*image: none; */\n"
"    nosubcontrol-origin: margin;\n"
"    subcontrol-position: right center;\n"
"    margin-top: 10px;\n"
"    width:20px;\n"
"}\n"
"\n"
"/* Style for calendar table ########################################## */\n"
"#qt_calendar_calendarview {\n"
"    /* Remove the selected dashed box */\n"
"    outline: 0px;\n"
"\n"
"    border: 2px solid  #B8E2FF;\n"
"    border-top: 0px;\n"
"    border-bottom-left-radius: 5px;\n"
"    border-bottom-right-radius: 5px;\n"
"}\n"
"\n"
"#qt_calendar_calendarview::item:hover {\n"
"   border-radius:5px;\n"
"    /*background-color:#aaffff;*/\n"
"    background-color:rgb(163, 160, 255);\n"
"}\n"
"\n"
"#qt_calendar_calendarview::item:selected {\n"
"   /* background-color: #f3d739;*/\n"
"    background-color: rgb(255, 185, 46);\n"
"    color: rgb(0, 0, 0);\n"
"    border-radius:5px;\n"
"}\n"
"")
        self.calendario.setMinimumDate(QtCore.QDate(2025, 5, 1))
        self.calendario.setGridVisible(True)
        self.calendario.setSelectionMode(QtWidgets.QCalendarWidget.SelectionMode.SingleSelection)
        self.calendario.setObjectName("calendario")
        self.verticalLayout_2.addWidget(self.calendario, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.gridLayout_3.addWidget(self.QFram_Calendario, 0, 0, 1, 3)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.Fechaselec.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:14pt; font-weight:700; color:#000000;\">Fecha selecionada:</span></p><p><br/></p><p><span style=\" font-size:14pt; font-weight:700; color:#ffffff;\"><br/></span></p></body></html>"))
        self.SigVentana.setText(_translate("Form", "Confirmar"))
        self.SelFecha.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:16pt; font-weight:700; font-style:italic;\">Seleccione Fecha</span></p></body></html>"))
