# Form implementation generated from reading ui file 'Window_Satelites.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(856, 555)
        Form.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        Form.setStyleSheet("QPushButton {\n"
"    min-height: 40px;\n"
"}\n"
"")
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.QFrame_Tabla = QtWidgets.QFrame(parent=Form)
        self.QFrame_Tabla.setStyleSheet("background-color: rgb(221, 221, 221);")
        self.QFrame_Tabla.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.QFrame_Tabla.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.QFrame_Tabla.setObjectName("QFrame_Tabla")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.QFrame_Tabla)
        self.verticalLayout_2.setContentsMargins(-1, 5, -1, -1)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.fecha_entrada = QtWidgets.QLabel(parent=self.QFrame_Tabla)
        self.fecha_entrada.setObjectName("fecha_entrada")
        self.verticalLayout_2.addWidget(self.fecha_entrada, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.frame = QtWidgets.QFrame(parent=self.QFrame_Tabla)
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.SelectAll = QtWidgets.QCheckBox(parent=self.frame)
        self.SelectAll.setText("")
        self.SelectAll.setObjectName("SelectAll")
        self.verticalLayout_3.addWidget(self.SelectAll)
        self.verticalLayout_2.addWidget(self.frame)
        self.tablaSatelites = QtWidgets.QTableWidget(parent=self.QFrame_Tabla)
        self.tablaSatelites.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.tablaSatelites.setObjectName("tablaSatelites")
        self.tablaSatelites.setColumnCount(0)
        self.tablaSatelites.setRowCount(0)
        self.verticalLayout_2.addWidget(self.tablaSatelites)
        self.verticalLayout.addWidget(self.QFrame_Tabla)
        self.QFrame_Botones = QtWidgets.QFrame(parent=Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.QFrame_Botones.sizePolicy().hasHeightForWidth())
        self.QFrame_Botones.setSizePolicy(sizePolicy)
        self.QFrame_Botones.setMinimumSize(QtCore.QSize(0, 74))
        self.QFrame_Botones.setMaximumSize(QtCore.QSize(16777215, 74))
        self.QFrame_Botones.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.QFrame_Botones.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.QFrame_Botones.setObjectName("QFrame_Botones")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.QFrame_Botones)
        self.horizontalLayout.setContentsMargins(9, 0, 9, 0)
        self.horizontalLayout.setSpacing(26)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.BotonSubir = QtWidgets.QPushButton(parent=self.QFrame_Botones)
        self.BotonSubir.setMinimumSize(QtCore.QSize(0, 44))
        self.BotonSubir.setStyleSheet("QPushButton{\n"
"\n"
"    background-color: rgb(153, 255, 58);\n"
"    \n"
"    border-style: outset;\n"
"    border-width: 2px;\n"
"    border-color: grey;\n"
"    border-radius: 10\n"
"}\n"
"QPushButton:hover {\n"
"    border-style: inset;\n"
"}\n"
"QPushButton:pressed{\n"
"    border-style: inset;\n"
"    \n"
"    \n"
"    background-color: rgb(130, 217, 49);\n"
"}\n"
"")
        self.BotonSubir.setObjectName("BotonSubir")
        self.horizontalLayout.addWidget(self.BotonSubir)
        self.BotonAddSessions = QtWidgets.QPushButton(parent=self.QFrame_Botones)
        self.BotonAddSessions.setStyleSheet("QPushButton{\n"
"    background-color: rgb(255, 255, 255);\n"
"    border-style: outset;\n"
"    border-width: 2px;\n"
"    border-color: grey;\n"
"    border-radius: 10\n"
"}\n"
"QPushButton:hover {\n"
"    border-style: inset;\n"
"}\n"
"QPushButton:pressed{\n"
"    border-style: inset;\n"
"    \n"
"    background-color: rgb(239, 239, 239);\n"
"}")
        self.BotonAddSessions.setObjectName("BotonAddSessions")
        self.horizontalLayout.addWidget(self.BotonAddSessions)
        self.BotonProcMan = QtWidgets.QPushButton(parent=self.QFrame_Botones)
        self.BotonProcMan.setStyleSheet("QPushButton{\n"
"    background-color: rgb(255, 255, 255);\n"
"    border-style: outset;\n"
"    border-width: 2px;\n"
"    border-color: grey;\n"
"    border-radius: 10\n"
"}\n"
"QPushButton:hover {\n"
"    border-style: inset;\n"
"}\n"
"QPushButton:pressed{\n"
"    border-style: inset;\n"
"    \n"
"    background-color: rgb(239, 239, 239);\n"
"}")
        self.BotonProcMan.setObjectName("BotonProcMan")
        self.horizontalLayout.addWidget(self.BotonProcMan)
        self.BotonProcAuto = QtWidgets.QPushButton(parent=self.QFrame_Botones)
        self.BotonProcAuto.setStyleSheet("QPushButton{\n"
"    background-color: rgb(255, 255, 255);\n"
"    border-style: outset;\n"
"    border-width: 2px;\n"
"    border-color: grey;\n"
"    border-radius: 10\n"
"}\n"
"QPushButton:hover {\n"
"    border-style: inset;\n"
"}\n"
"QPushButton:pressed{\n"
"    border-style: inset;\n"
"    \n"
"    background-color: rgb(239, 239, 239);\n"
"}")
        self.BotonProcAuto.setObjectName("BotonProcAuto")
        self.horizontalLayout.addWidget(self.BotonProcAuto)
        self.BotonBorrar = QtWidgets.QPushButton(parent=self.QFrame_Botones)
        self.BotonBorrar.setStyleSheet("QPushButton{\n"
"    background-color: rgb(255, 170, 0);\n"
"    border-style: outset;\n"
"    border-width: 2px;\n"
"    border-color: grey;\n"
"    border-radius: 10\n"
"}\n"
"QPushButton:hover {\n"
"    border-style: inset;\n"
"}\n"
"QPushButton:pressed{\n"
"    border-style: inset;\n"
"    \n"
"    \n"
"    background-color: rgb(222, 148, 0);\n"
"}")
        self.BotonBorrar.setObjectName("BotonBorrar")
        self.horizontalLayout.addWidget(self.BotonBorrar)
        self.verticalLayout.addWidget(self.QFrame_Botones)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Sesion seleccionada"))
        self.fecha_entrada.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:14pt; font-weight:700;\">Fecha: 14/01/2003</span></p></body></html>"))
        self.BotonSubir.setText(_translate("Form", "Subir Pases Seleccionados"))
        self.BotonAddSessions.setText(_translate("Form", "Añadir Sesiones"))
        self.BotonProcMan.setText(_translate("Form", "Procesado Manual"))
        self.BotonProcAuto.setText(_translate("Form", "Procesado Automático"))
        self.BotonBorrar.setText(_translate("Form", "Borrar Pases Seleccionados"))
