# Form implementation generated from reading ui file 'Window_Sesiones.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(855, 418)
        Form.setStyleSheet("background-color: rgb(221, 221, 221);")
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.QFrame_Contenido = QtWidgets.QFrame(parent=Form)
        self.QFrame_Contenido.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.QFrame_Contenido.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.QFrame_Contenido.setObjectName("QFrame_Contenido")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.QFrame_Contenido)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.QFrame_Tabla = QtWidgets.QFrame(parent=self.QFrame_Contenido)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.QFrame_Tabla.sizePolicy().hasHeightForWidth())
        self.QFrame_Tabla.setSizePolicy(sizePolicy)
        self.QFrame_Tabla.setMinimumSize(QtCore.QSize(552, 400))
        self.QFrame_Tabla.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.QFrame_Tabla.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.QFrame_Tabla.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.QFrame_Tabla.setObjectName("QFrame_Tabla")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.QFrame_Tabla)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.fecha_entrada = QtWidgets.QLabel(parent=self.QFrame_Tabla)
        self.fecha_entrada.setMinimumSize(QtCore.QSize(171, 31))
        self.fecha_entrada.setObjectName("fecha_entrada")
        self.verticalLayout_3.addWidget(self.fecha_entrada)
        self.listaCarpetas = QtWidgets.QListWidget(parent=self.QFrame_Tabla)
        self.listaCarpetas.setMinimumSize(QtCore.QSize(531, 30))
        self.listaCarpetas.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.listaCarpetas.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.listaCarpetas.setObjectName("listaCarpetas")
        self.verticalLayout_3.addWidget(self.listaCarpetas)
        self.horizontalLayout.addWidget(self.QFrame_Tabla, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.QFrame_Botones = QtWidgets.QFrame(parent=self.QFrame_Contenido)
        self.QFrame_Botones.setMaximumSize(QtCore.QSize(500, 16777215))
        self.QFrame_Botones.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.QFrame_Botones.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.QFrame_Botones.setObjectName("QFrame_Botones")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.QFrame_Botones)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_4.addItem(spacerItem)
        self.BotonRecargar = QtWidgets.QPushButton(parent=self.QFrame_Botones)
        self.BotonRecargar.setMinimumSize(QtCore.QSize(121, 51))
        self.BotonRecargar.setStyleSheet("QPushButton{\n"
"    background-color: rgb(255, 255, 255);\n"
"    border-style: outset;\n"
"    border-width: 2px;\n"
"    border-color: grey;\n"
"    border-radius: 10\n"
"}\n"
"QPushButton:hover {\n"
"    border-style: inset;\n"
"}\n"
"QPushButton:pressed{\n"
"    border-style: inset;\n"
"    \n"
"    background-color: rgb(239, 239, 239);\n"
"}")
        self.BotonRecargar.setObjectName("BotonRecargar")
        self.verticalLayout_4.addWidget(self.BotonRecargar)
        self.BotonVeri = QtWidgets.QPushButton(parent=self.QFrame_Botones)
        self.BotonVeri.setMinimumSize(QtCore.QSize(161, 51))
        self.BotonVeri.setStyleSheet("QPushButton{\n"
"    background-color: rgb(255, 255, 255);\n"
"    border-style: outset;\n"
"    border-width: 2px;\n"
"    border-color: grey;\n"
"    border-radius: 10\n"
"}\n"
"QPushButton:hover {\n"
"    border-style: inset;\n"
"}\n"
"QPushButton:pressed{\n"
"    border-style: inset;\n"
"    \n"
"    background-color: rgb(239, 239, 239);\n"
"}")
        self.BotonVeri.setObjectName("BotonVeri")
        self.verticalLayout_4.addWidget(self.BotonVeri)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_4.addItem(spacerItem1)
        self.horizontalLayout.addWidget(self.QFrame_Botones)
        self.verticalLayout.addWidget(self.QFrame_Contenido, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Sesiones"))
        self.fecha_entrada.setText(_translate("Form", "<html><head/><body><p align=\"right\"><span style=\" font-size:14pt; font-weight:700;\">Fecha: 14/01/2003</span></p></body></html>"))
        self.BotonRecargar.setText(_translate("Form", "Recargar"))
        self.BotonVeri.setText(_translate("Form", "Confirmar Selección"))
